Restart apache2 early to make sure the certbot module works

diff --git a/himbeerserver/DEBIAN/postinst b/himbeerserver/DEBIAN/postinst
--- a/himbeerserver/DEBIAN/postinst
+++ b/himbeerserver/DEBIAN/postinst
@@ -61,13 +61,6 @@ if [ $? != 0 ]; then
 	exit 1
 fi
 
-certbot --apache -n --agree-tos --email "$EMAIL" --domains "$DOMAIN,www.$DOMAIN" \
-		--redirect
-if [ $? != 0 ]; then
-	echo -e " [\e[31m✗\e[0m] Error installing himbeerserver, see above"
-	exit 1
-fi
-
 echo -en " [i] Restarting apache2 ...\r"
 
 service apache2 restart
@@ -77,4 +70,21 @@ if [ $? != 0 ]; then
 fi
 
 echo -e " [\e[32m✓\e[0m] Restarted apache2     "
+
+certbot --apache -n --agree-tos --email "$EMAIL" --domains "$DOMAIN,www.$DOMAIN" \
+		--redirect
+if [ $? != 0 ]; then
+	echo -e " [\e[31m✗\e[0m] Error installing himbeerserver, see above"
+	exit 1
+fi
+
+echo -en " [i] Restarting apache2 again ...\r"
+
+service apache2 restart
+if [ $? != 0 ]; then
+	echo -e " [\e[31m✗\e[0m] Error installing himbeerserver, see above"
+	exit 1
+fi
+
+echo -e " [\e[32m✓\e[0m] Restarted apache2 again     "
 echo -e " [\e[32m✓\e[0m] Successfully installed himbeerserver"
