Delete config when package is purged

diff --git a/himbeerserver/DEBIAN/postinst b/himbeerserver/DEBIAN/postinst
--- a/himbeerserver/DEBIAN/postinst
+++ b/himbeerserver/DEBIAN/postinst
@@ -16,6 +16,22 @@ fi
 
 echo -e " [\e[32m✓\e[0m] Replaced 000-default.conf     "
 
+a2enmod cgi
+if [ $? != 0 ]; then
+	echo -e " [\e[31m✗\e[0m] Error installing himbeerserver, see above"
+	exit 1
+fi
+
+echo -en " [i] Restarting apache2 ...\r"
+
+service apache2 restart
+if [ $? != 0 ]; then
+	echo -e " [\e[31m✗\e[0m] Error installing himbeerserver, see above"
+	exit 1
+fi
+
+echo -e " [\e[32m✓\e[0m] Restarted apache2     "
+
 luarocks install http
 if [ $? != 0 ]; then
 	echo -e " [\e[31m✗\e[0m] Error installing himbeerserver, see above"
