Fix installation on new system

diff --git a/himbeerserver/DEBIAN/postinst b/himbeerserver/DEBIAN/postinst
--- a/himbeerserver/DEBIAN/postinst
+++ b/himbeerserver/DEBIAN/postinst
@@ -1,5 +1,21 @@
 #!/bin/bash
 
+echo -en " [i] Replacing 000-default.conf ...\r"
+
+rm /etc/apache2/sites-available/000-default.conf
+if [ $? != 0 ]; then
+	echo -e " [\e[31m✗\e[0m] Error installing himbeerserver, see above"
+	exit 1
+fi
+
+ln -s /etc/himbeerserver/000-default.conf /etc/apache2/sites-available/000-default.conf
+if [ $? != 0 ]; then
+	echo -e " [\e[31m✗\e[0m] Error installing himbeerserver, see above"
+	exit 1
+fi
+
+echo -e " [\e[32m✓\e[0m] Replaced 000-default.conf     "
+
 luarocks install http
 if [ $? != 0 ]; then
 	echo -e " [\e[31m✗\e[0m] Error installing himbeerserver, see above"
