Simplify concept

diff --git a/himbeerserver/DEBIAN/postinst b/himbeerserver/DEBIAN/postinst
--- a/himbeerserver/DEBIAN/postinst
+++ b/himbeerserver/DEBIAN/postinst
@@ -60,10 +60,13 @@ if [ $? != 0 ]; then
 	exit 1
 fi
 
-certbot --apache -n --agree-tos --email "$EMAIL" --domains "$DOMAIN,www.$DOMAIN"
-if [ $? != 0 ]; then
-	echo -e " [\e[31m✗\e[0m] Error installing himbeerserver (certbot), see above"
-	exit 1
+db_get himbeerserver/run_certbot
+if [ "$RET" == "true" ]; then
+	certbot --apache -n --agree-tos --email "$EMAIL" --domains "$DOMAIN,www.$DOMAIN"
+	if [ $? != 0 ]; then
+		echo -e " [\e[31m✗\e[0m] Error installing himbeerserver, see above"
+		exit 1
+	fi
 fi
 
 echo -en " [i] Restarting apache2 ...\r"
@@ -76,16 +79,25 @@ fi
 
 echo -e " [\e[32m✓\e[0m] Restarted apache2     "
 
-luarocks install http
-if [ $? != 0 ]; then
-	echo -e " [\e[31m✗\e[0m] Error installing himbeerserver, see above"
-	exit 1
-fi
-
 luarocks install lunajson
 if [ $? != 0 ]; then
 	echo -e " [\e[31m✗\e[0m] Error installing himbeerserver, see above"
 	exit 1
 fi
 
+echo -en " [i] Markdown -> HTML ...\r"
+
+STATIC=`find /var/www/md -name "*.md"`
+for FILE in $STATIC; do
+	HTML=`echo "$FILE" | sed "s/\/md/\/html/" | sed "s/\\.md/\\.html/g"`
+	TITLE=`head -n 1 "$FILE" | sed "s/<!-- //" | sed "s/ -->//"`
+
+	pandoc --standalone --metadata title="$TITLE" "$FILE" -o "$HTML" 2>/dev/null
+	if [ $? != 0 ]; then
+		echo -e " [\e[31m✗\e[0m] Error installing himbeerserver, see above"
+		exit 1
+	fi
+done
+
+echo -e " [\e[32m✓\e[0m] Markdown -> HTML    "
 echo -e " [\e[32m✓\e[0m] Successfully installed himbeerserver"
